services:
  - type: web
    name: job-role-management-system
    env: node
    rootDir: .
    buildCommand: npm install && npm run build --workspace client
    startCommand: npm run start --workspace server
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_NAME
        value: Admin User
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        sync: false
